export interface Processo {
  ID_PROCESSO: string | String;
  NUMERO_PROCESSO: string | String;
  STATUS: string | String;
  TIPO_DE_ACAO: string | String;
  AREA_DO_DIREITO: string | String;
  EMPRESA: string | String;
  EMPRESA_CNPJ: string;
  AMBITO: string | String;
  ESTADO: string | String;
  CIDADE: string | String;
  PAIS: string | String;
  VARA: string | String;
  FORO_TRIBUNAL_ORGAO: string | String;
  FASE: string | String;
  DATA_DISTRIBUICAO: Date;
  DATA_CITACAO: Date;
  PATRONO_RESPONSAVEL: string | String;
  PATRONOS_ANTERIORES: string | String;
  TEXTO_DO_OBJETO: string | String;
  VALOR_DO_PEDIDO: Number;
  VALOR_INSTANCIA1: Number;
  VALOR_INSTANCIA2: Number;
  VALOR_INSTANCIA3: Number;
  VALOR_INSTANCIA_EXTRAORDINARIA: Number;
  DATA_CADASTRO_PROCESSO: Date;
  DATA_ULTIMO_ANDAMENTO: Date;
  DATA_ENCERRAMENTO: Date;
  MOTIVO_ENCERRAMENTO: string | String;
  MOTIVO_BAIXA_PROVISORIA: string | String;
}